CREATE DATABASE LIBRARY_SYSTEM_002
GO

USE LIBRARY_SYSTEM_002

CREATE TABLE AUTHOR (
	AUTHOR_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	AUTHOR_NAME VARCHAR(20) NOT NULL
)

CREATE TABLE [GENRE] (
	GENRE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	GENRE VARCHAR(15) NOT NULL
)

CREATE TABLE PUBLISHER (
	PUBLISHER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PUBLISHER_NAME VARCHAR(50) NOT NULL
)

CREATE TABLE [CATALOG] (
	CATALOG_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CATALOG_NAME VARCHAR(20) NOT NULL,
	CREATION_DATE DATE NOT NULL
)

CREATE TABLE PENALTY (
	PENALTY_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PENALTY_DESCRIPTION VARCHAR(100) NOT NULL,
	PENALTY_DUEDATE DATE NOT NULL
)

CREATE INDEX IDX_PENALTYDESC ON PENALTY(PENALTY_DESCRIPTION)

CREATE TABLE [NOTIFICATION] (
	NOTIF_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOTIF_DESCRIPTION VARCHAR(100) NOT NULL,
	PENALTY_ID INT REFERENCES PENALTY(PENALTY_ID) NOT NULL
)

CREATE INDEX IDX_NOTIFDESC ON [NOTIFICATION](NOTIF_DESCRIPTION)

CREATE TABLE LIBRARIAN (
	LIBRARIAN_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	LIBRARIAN_FNAME VARCHAR(20) NOT NULL,
	LIBRARIAN_LNAME VARCHAR(20) NOT NULL,
	LIBRARIAN_FULLNAME AS (LIBRARIAN_FNAME+' '+LIBRARIAN_LNAME),
	NOTIF_ID INT REFERENCES [NOTIFICATION](NOTIF_ID) NOT NULL
)
ALTER TABLE LIBRARIAN
DROP COLUMN LIBRARIAN_ROLE


CREATE INDEX IDX_LIBRARIANNAME ON LIBRARIAN(LIBRARIAN_FNAME,LIBRARIAN_LNAME)

CREATE TABLE BORROWER (
	BORROWER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BORROWER_FNAME VARCHAR(20) NOT NULL,
	BORROWER_LNAME VARCHAR(20) NOT NULL,
	BORROWER_FULLNAME AS (BORROWER_FNAME+' '+BORROWER_LNAME),
	BORROWER_VALIDID VARCHAR(20) NOT NULL,
	BORROWER_PHOTO VARCHAR(50) NOT NULL,
	PHONE_NUMBER INT NOT NULL,
	EMAIL VARCHAR(20) NOT NULL,
	NOTIF_ID INT REFERENCES [NOTIFICATION](NOTIF_ID) NOT NULL
)

CREATE INDEX IDX_BORROWERNAME ON BORROWER(BORROWER_FNAME,BORROWER_LNAME)

CREATE TABLE SHELF (
	SHELF_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	SHELF_NUMBER INT NOT NULL,
	GENRE_ID INT REFERENCES GENRE(GENRE_ID) NOT NULL
)

CREATE TABLE BOOK (
	BOOKID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BOOK_TITLE VARCHAR(50) NOT NULL,
	PUBLICATION_DATE DATE NOT NULL,
	AUTHOR_ID INT REFERENCES AUTHOR(AUTHOR_ID) NOT NULL,
	GENRE_ID INT REFERENCES [GENRE](GENRE_ID) NOT NULL,
	PUBLISHER_ID INT REFERENCES PUBLISHER(PUBLISHER_ID) NOT NULL,
	CATALOG_ID INT REFERENCES [CATALOG](CATALOG_ID) NOT NULL,
	SHELF_ID INT REFERENCES SHELF(SHELF_ID) NOT NULL
)

CREATE INDEX IDX_BOOKTITLE ON BOOK(BOOK_TITLE)

CREATE TABLE CHECKOUT (
	CHECKOUT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BORROWER_ID INT REFERENCES BORROWER(BORROWER_ID) NOT NULL,
	LIBRARIAN_ID INT REFERENCES LIBRARIAN(LIBRARIAN_ID) NOT NULL,
	BOOK_ID INT REFERENCES BOOK(BOOKID) NOT NULL,
	CHECKOUT_DATE DATE NOT NULL,
	DUE_DATE DATE NOT NULL
)

--INSERT INTO [CATALOG](CATALOG_NAME,CREATION_DATE) VALUES('New Catalog','2022-01-01')
--INSERT INTO SHELF(SHELF_NUMBER,GENRE_ID) VALUES(3,3)
--INSERT INTO BOOK(BOOK_TITLE,PUBLICATION_DATE,AUTHOR_ID,GENRE_ID,PUBLISHER_ID,CATALOG_ID,SHELF_ID)
--VALUES ('Harry Potter','2022-01-01',3,3,2,2,4)

SELECT * FROM AUTHOR
SELECT * FROM GENRE
SELECT * FROM BORROWER